apiVersion: v1
kind: Service
metadata:
  namespace: npu-exporter        # Namespace of the npu-exporter service.
  name: npu-exporter             # Name of the npu-exporter service.
  labels:                        # Labels of the npu-exporter service.
    app: npu-exporter-svc
spec:
  type: ClusterIP
  ports:
  - port: 8082             # Port of the npu-exporter service.
    targetPort: 8082       # Port of the npu-exporter pod, it should be the same as the port that the pod of npu-exporter is listening on.
    protocol: TCP
    name: http
  selector:                # Matching labels, it should match the labels of the npu-exporter pod.
    app: npu-exporter
